import '../../domain/models.dart';
import 'catalog_seed_types.dart';

List<SkillSeedBundle> buildSkillSeeds(String stamp) {
  SkillSeedBundle skill({
    required String id,
    required String title,
    required String summary,
    required String scenario,
    required ResourceDifficulty difficulty,
    required List<String> tags,
    required String capabilitySummary,
    required List<String> inputRequirements,
    required List<String> usageSteps,
    required List<String> supportedModels,
    required String copyPayload,
    required Map<String, dynamic> rawSchema,
    required Map<String, dynamic> providerAdapters,
    required String exampleCode,
    required String exampleLanguage,
    bool featured = false,
  }) {
    return buildSkillSeed(
      id: id,
      title: title,
      summary: summary,
      scenario: scenario,
      difficulty: difficulty,
      tags: tags,
      capabilitySummary: capabilitySummary,
      inputRequirements: inputRequirements,
      usageSteps: usageSteps,
      supportedModels: supportedModels,
      copyPayload: copyPayload,
      rawSchema: rawSchema,
      providerAdapters: providerAdapters,
      exampleCode: exampleCode,
      exampleLanguage: exampleLanguage,
      featured: featured,
      stamp: stamp,
    );
  }

  const allAdapters = {
    'openai': true,
    'anthropic': true,
    'gemini': true,
  };

  return [
    skill(
      id: 'skill-structured-minutes',
      title: '会议纪要结构化',
      summary: '把混乱会议记录整理成结论、待办、负责人和时间点。',
      scenario: '办公协作',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['会议', '纪要', '结构化'],
      capabilitySummary: '适合把语音转写、聊天摘录和手写纪要快速整理成可执行版本。',
      inputRequirements: const ['会议原文', '如有则补充会议主题'],
      usageSteps: const [
        '粘贴会议原文或转写稿',
        '补充会议主题与参与角色',
        '让模型按结论、待办、负责人输出',
      ],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini', 'DeepSeek'],
      copyPayload:
          '技能名：会议纪要结构化\n输入：meeting_text, meeting_topic\n输出：会议结论、待办事项、负责人、截止时间',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'meeting_text': {'type': 'string'},
          'meeting_topic': {'type': 'string'},
        },
        'required': ['meeting_text'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "meeting_text": "今天我们讨论首页改版...",\n  "meeting_topic": "资源库首页优化"\n}',
      exampleLanguage: 'json',
      featured: true,
    ),
    skill(
      id: 'skill-prompt-scorer',
      title: '提示词评分器',
      summary: '判断一条提示词是否清晰、具体、可执行，并给出改写方向。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['提示词', '评估', '优化'],
      capabilitySummary: '适合提示词迭代时做第一轮体检，减少模糊表达和输出不稳定。',
      inputRequirements: const ['提示词原文', '目标任务'],
      usageSteps: const [
        '粘贴原始提示词',
        '补充任务目标或目标模型',
        '查看评分、缺失项和建议改写',
      ],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：提示词评分器\n输入：prompt_text, goal\n输出：清晰度评分、缺失项、建议改写',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'prompt_text': {'type': 'string'},
          'goal': {'type': 'string'},
        },
        'required': ['prompt_text', 'goal'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "prompt_text": "帮我写点文案",\n  "goal": "生成一条小红书笔记草稿"\n}',
      exampleLanguage: 'json',
      featured: true,
    ),
    skill(
      id: 'skill-requirement-todo',
      title: '需求转任务清单',
      summary: '把模糊需求拆成功能块、依赖、风险和可执行任务清单。',
      scenario: '办公协作',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['需求', '任务', '项目管理'],
      capabilitySummary: '适合产品、研发和运营一起收口需求边界。',
      inputRequirements: const ['需求描述', '时间约束或上线目标'],
      usageSteps: const ['粘贴需求', '补充上线目标', '输出任务拆解与依赖顺序'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini', 'DeepSeek'],
      copyPayload:
          '技能名：需求转任务清单\n输入：requirement, deadline\n输出：功能拆解、依赖、风险、建议排期',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'requirement': {'type': 'string'},
          'deadline': {'type': 'string'},
        },
        'required': ['requirement'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "requirement": "把官方资源做成动态下发目录",\n  "deadline": "两周内可用"\n}',
      exampleLanguage: 'json',
      featured: true,
    ),
    skill(
      id: 'skill-content-labeler',
      title: '内容标签归类',
      summary: '对文章、笔记、脚本或素材做统一标签归类，方便后续检索与分发。',
      scenario: '内容增长',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['内容运营', '标签', '归类'],
      capabilitySummary: '适合内容资产管理和多平台分发前的标准化整理。',
      inputRequirements: const ['标题', '正文或摘要'],
      usageSteps: const ['输入内容', '要求输出标签和主题', '人工确认后入库'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：内容标签归类\n输入：title, content\n输出：主题标签、适用平台、内容类型',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'title': {'type': 'string'},
          'content': {'type': 'string'},
        },
        'required': ['content'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "title": "提示词、技能与 MCP 的区别",\n  "content": "本文解释三者差异..."\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-customer-intent',
      title: '用户意图归因',
      summary: '把客服消息、评论或反馈分成咨询、抱怨、退款、建议等类型。',
      scenario: '内容增长',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['客服', '用户反馈', '分类'],
      capabilitySummary: '适合客服提效、问题归档和高频问题统计。',
      inputRequirements: const ['用户原话'],
      usageSteps: const ['输入用户原话', '返回意图分类', '补充建议回复方向'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：用户意图归因\n输入：message\n输出：意图分类、紧急程度、建议回复策略',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'message': {'type': 'string'},
        },
        'required': ['message'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "message": "为什么我打开后一直转圈？"\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-api-doc-generator',
      title: '接口文档生成器',
      summary: '把接口契约自动整理成更可读的开发文档。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['API', '文档', '后端'],
      capabilitySummary: '适合从 OpenAPI、字段说明和代码注释自动整理对外文档。',
      inputRequirements: const ['接口定义', '目标读者'],
      usageSteps: const ['粘贴接口字段', '指定读者', '输出结构化文档'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：接口文档生成器\n输入：api_contract, audience\n输出：用途、参数表、响应表、示例调用',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'api_contract': {'type': 'string'},
          'audience': {'type': 'string'},
        },
        'required': ['api_contract'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "api_contract": "GET /v1/catalog/resources",\n  "audience": "前端工程师"\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-bug-report-normalizer',
      title: '缺陷报告标准化',
      summary: '把口语化 bug 反馈整理成研发可处理的缺陷单。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['缺陷', '缺陷单', '排障'],
      capabilitySummary: '适合把群聊抱怨、测试口述和截图说明转成标准缺陷报告。',
      inputRequirements: const ['原始反馈', '环境信息（可选）'],
      usageSteps: const ['输入原始反馈', '补充环境', '输出复现步骤、预期结果和风险'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：缺陷报告标准化\n输入：raw_feedback, environment\n输出：复现步骤、实际结果、预期结果、影响范围',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'raw_feedback': {'type': 'string'},
          'environment': {'type': 'string'},
        },
        'required': ['raw_feedback'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "raw_feedback": "点我的页面一直转圈，什么都进不去",\n  "environment": "Windows 调试构建"\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-skill-creator',
      title: '技能设计助手',
      summary: '参考 skills.sh 和 Agent 最佳实践，帮助你设计一条可复用技能。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.intermediate,
      tags: const ['skills.sh', '技能设计', 'Agent'],
      capabilitySummary: '适合把一次性的好方法抽象成稳定可复用的技能模板。',
      inputRequirements: const ['要解决的任务', '输入输出边界'],
      usageSteps: const ['描述任务', '明确输入输出', '生成技能说明、Schema 和接入建议'],
      supportedModels: const ['Claude', 'ChatGPT', 'Gemini'],
      copyPayload:
          '技能名：技能设计助手\n输入：task_description, inputs, outputs\n输出：技能描述、使用步骤、Schema 草案',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'task_description': {'type': 'string'},
          'inputs': {'type': 'array', 'items': {'type': 'string'}},
          'outputs': {'type': 'array', 'items': {'type': 'string'}},
        },
        'required': ['task_description'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "task_description": "把会议记录整理成纪要",\n  "inputs": ["meeting_text"],\n  "outputs": ["summary", "todos"]\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-webapp-testing',
      title: '网页应用测试助手',
      summary: '参考 skills.sh 的 webapp-testing 思路，把页面测试拆成操作、观察、验证。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.intermediate,
      tags: const ['测试', 'UI', 'skills.sh'],
      capabilitySummary: '适合规划测试路径、验证关键流程和沉淀回归步骤。',
      inputRequirements: const ['页面目标', '关键流程', '预期结果'],
      usageSteps: const ['列目标页面', '拆关键路径', '输出测试步骤与验证点'],
      supportedModels: const ['Claude', 'ChatGPT', 'Gemini'],
      copyPayload:
          '技能名：网页应用测试助手\n输入：goal, flows, expected_outcomes\n输出：测试路径、检查点、异常记录格式',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'goal': {'type': 'string'},
          'flows': {'type': 'array', 'items': {'type': 'string'}},
          'expected_outcomes': {'type': 'array', 'items': {'type': 'string'}},
        },
        'required': ['goal', 'flows'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "goal": "验证首页首屏对新手是否友好",\n  "flows": ["进入首页", "点击新手合集", "查看详情页"]\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-github-cli-workflow',
      title: 'GitHub 命令行工作流',
      summary: '参考 skills.sh 的 gh-cli 类能力，把 PR、Issue、评论处理流程固定下来。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.intermediate,
      tags: const ['GitHub', 'CLI', '协作'],
      capabilitySummary: '适合处理 PR 评论、查看 CI、整理 Issue 上下文和标准提交动作。',
      inputRequirements: const ['仓库上下文', '目标操作'],
      usageSteps: const ['说明当前 PR/Issue', '选择操作目标', '生成标准命令与执行顺序'],
      supportedModels: const ['Claude', 'ChatGPT'],
      copyPayload:
          '技能名：GitHub 命令行工作流\n输入：repo_context, task\n输出：命令顺序、核对点、风险提示',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'repo_context': {'type': 'string'},
          'task': {'type': 'string'},
        },
        'required': ['task'],
      },
      providerAdapters: const {'openai': true, 'anthropic': true},
      exampleCode: '{\n  "repo_context": "处理一个被要求补测试的 PR",\n  "task": "查看未解决评论并生成修复步骤"\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-supabase-postgres',
      title: 'Supabase / Postgres 最佳实践',
      summary: '参考 skills.sh 的数据库技能，帮助你把 SQL、索引和表设计建议说清楚。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.intermediate,
      tags: const ['Postgres', 'Supabase', '数据库'],
      capabilitySummary: '适合表设计评审、慢查询定位和 RLS 规则梳理。',
      inputRequirements: const ['表结构或 SQL', '当前问题'],
      usageSteps: const ['输入表结构', '描述问题', '输出优化方向和风险'],
      supportedModels: const ['Claude', 'ChatGPT', 'Gemini'],
      copyPayload:
          '技能名：Supabase / Postgres 最佳实践\n输入：schema_or_sql, issue\n输出：性能建议、数据建模建议、安全提醒',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'schema_or_sql': {'type': 'string'},
          'issue': {'type': 'string'},
        },
        'required': ['schema_or_sql'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "schema_or_sql": "SELECT * FROM events WHERE created_at >= ?",\n  "issue": "查询高峰期超时"\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-react-native-delivery',
      title: '跨端交付规划',
      summary: '参考 skills.sh 的 React Native / Vercel 类技能，把跨端交付拆成里程碑和风险。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.intermediate,
      tags: const ['跨端', '交付', '规划'],
      capabilitySummary: '适合把“做个 App/站点”这种大需求拆成可交付阶段。',
      inputRequirements: const ['产品目标', '技术约束'],
      usageSteps: const ['说明目标', '列约束', '输出阶段计划和验收点'],
      supportedModels: const ['Claude', 'ChatGPT', 'Gemini'],
      copyPayload:
          '技能名：跨端交付规划\n输入：goal, constraints\n输出：里程碑、风险、验收标准',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'goal': {'type': 'string'},
          'constraints': {'type': 'string'},
        },
        'required': ['goal'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "goal": "做一款本地优先的 AI 资源库 App",\n  "constraints": "Flutter 前端，Go 后端，自托管同步"\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-sql-explainer',
      title: 'SQL 解释与教学',
      summary: '把复杂 SQL 拆成“它在做什么、为什么慢、该怎么改”。',
      scenario: '开发提效',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['SQL', '解释', '教学'],
      capabilitySummary: '适合让团队新同学快速理解遗留 SQL 和报表查询。',
      inputRequirements: const ['SQL', '表结构（可选）'],
      usageSteps: const ['输入 SQL', '补充表结构', '输出逐段解释与风险提示'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：SQL 解释与教学\n输入：sql, schema\n输出：逐段解释、瓶颈判断、改写建议',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'sql': {'type': 'string'},
          'schema': {'type': 'string'},
        },
        'required': ['sql'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "sql": "SELECT u.id, COUNT(o.id) FROM users u LEFT JOIN orders o ON ...",\n  "schema": "users(id), orders(user_id, created_at)"\n}',
      exampleLanguage: 'sql',
    ),
    skill(
      id: 'skill-research-paper-reader',
      title: '论文速读技能',
      summary: '把论文内容压缩成背景、方法、实验、局限和可落地启发。',
      scenario: '求职成长',
      difficulty: ResourceDifficulty.intermediate,
      tags: const ['论文', '阅读', '总结'],
      capabilitySummary: '适合技术调研、前沿跟踪和快速判断是否值得精读。',
      inputRequirements: const ['论文内容或摘要', '阅读目标'],
      usageSteps: const ['输入论文内容', '指定阅读目标', '输出结构化摘要'],
      supportedModels: const ['Claude', 'ChatGPT', 'Gemini'],
      copyPayload:
          '技能名：论文速读技能\n输入：paper_text, reading_goal\n输出：问题、方法、实验、局限、启发',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'paper_text': {'type': 'string'},
          'reading_goal': {'type': 'string'},
        },
        'required': ['paper_text'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "paper_text": "The paper proposes...",\n  "reading_goal": "判断是否适合做资源检索增强"\n}',
      exampleLanguage: 'markdown',
    ),
    skill(
      id: 'skill-resume-highlights',
      title: '简历亮点提炼',
      summary: '从经历中提取更有招聘价值的亮点和关键词。',
      scenario: '求职成长',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['简历', '求职', '亮点'],
      capabilitySummary: '适合把模糊经历改成更清楚的结果表达和能力标签。',
      inputRequirements: const ['原始经历', '目标岗位'],
      usageSteps: const ['粘贴经历', '补充目标岗位', '输出亮点与改写版本'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：简历亮点提炼\n输入：experience, target_role\n输出：亮点摘要、关键词、改写建议',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'experience': {'type': 'string'},
          'target_role': {'type': 'string'},
        },
        'required': ['experience'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "experience": "负责资源目录重构与后端同步服务搭建",\n  "target_role": "全栈工程师"\n}',
      exampleLanguage: 'json',
    ),
    skill(
      id: 'skill-interview-followup',
      title: '面试追问生成器',
      summary: '根据经历生成高概率追问和答题结构。',
      scenario: '求职成长',
      difficulty: ResourceDifficulty.beginner,
      tags: const ['面试', '追问', '准备'],
      capabilitySummary: '适合项目复盘、模拟面试和补足表达盲区。',
      inputRequirements: const ['项目经历', '岗位方向'],
      usageSteps: const ['输入项目经历', '说明岗位方向', '输出追问和作答框架'],
      supportedModels: const ['ChatGPT', 'Claude', 'Gemini'],
      copyPayload:
          '技能名：面试追问生成器\n输入：project_story, target_role\n输出：追问问题、考察点、答题结构',
      rawSchema: const {
        'type': 'object',
        'properties': {
          'project_story': {'type': 'string'},
          'target_role': {'type': 'string'},
        },
        'required': ['project_story'],
      },
      providerAdapters: allAdapters,
      exampleCode: '{\n  "project_story": "从零设计一款本地优先的 AI 资源库 App",\n  "target_role": "产品技术负责人"\n}',
      exampleLanguage: 'json',
    ),
  ];
}
